name: 'Robot Framework'
description: 'Run Robot Framework tests'
runs:
  using: 'docker'
  image: docker://ppodgorsek/robot-framework:latest
  env:
    BROWSER: chrome
    ROBOT_TEST_DIR: ${GITHUB_WORKSPACE}/robot_tests
    ROBOT_REPORTS_DIR: ${GITHUB_WORKSPACE}/reports

